#+TITLE: Maximizing the Reach of Innovation
#+AUTHOR: Emilio Dorigatti
#+OPTIONS: toc:nil

# stupid word noobs
#+LATEX_HEADER: \usepackage[margin=2.5cm]{geometry}
#+LATEX_CLASS_OPTIONS: [12pt]
#+LATEX_HEADER: \usepackage[doublespacing]{setspace} 
#+LATEX_HEADER: \usepackage{mathptmx}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \setlength{\droptitle}{-1.0in}

* Background
Software products are ubiquitous and play an important role in most aspects of
people's lives. This hyper-connected world gives incredible visibility to
digital creators, and allows their works to reach a large part of the world's
population. In turn, everyone has the possibility to pick up a digital work and
add her personal touch on it, be it by adding new features, making it more
accessible, or fixing existing flaws. All of this gives every product the
potential of becoming a global phenomenon, at one condition: that the author
allows it.

* Goal of the Study
A good software products has a global reach, a great software product has a
global reach and gives its users the possibility of contributing to its
development; we call this its /innovation potential/, for anyone with a good
idea is not hampered to work on it. A natural question to ask is, then: \\

*Research Question:* Which steps should be taken to allow a new software
artifact reach the greatest number of people, and maximize its innovation
potential? \\

The focus of this question is not marketing; a successful answer to this
question would guide new entrepreneurs with innovative ideas follow the best
path to make their work benefit users the most, and raise awareness on toxic
business models which actively harm society in their relentless pursuit of
profit.

This question will be answered by a literature study on the topic of innovation,
and case studies on past innovative software products to showcase good and bad
ways to approach this issue. Among possible candidates in the digital world
there are the Open Source movement on one side, and patents and the Digital
Rights Management (DRM) system on the other. A possible case study are the
Operating System wars: Linux and Windows, or iOS and Android.


feedback:
focus on drm
forget business model

alternatives:
 - is drm and dmca really necessary?
    it's being abused in a number of cases, e.g. to prevent people from repairing tools
 - what factors affect the spread/adoption of scientific work/research?
    target: public or other researchers?
    https://en.wikipedia.org/wiki/Diffusion_of_innovations
    http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0019917#s1
    https://www.spreadingscience.com/
    https://www.eu2017.ee/sites/default/files/inline-files/Research%20and%20Innovation%20How%20to%20get%20more%20impact.pdf
    https://www.nature.com/articles/212449a0
        paywalled. oh, the irony
    http://www.sciencediffusion.com/
    https://pdfs.semanticscholar.org/c65d/4942c87a5814c7eca2ad33479a4529c1f611.pdf
       for the benefits of rapid dissemination of knowledge
    - reproducibility
          p-hacking, etc.
    - open source work (slightly related to the previous point)
        very strong in the deep learning community
    - paywall/open access
        https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4837983/
        https://phys.org/news/2017-08-paywall-journals.html
    - fake news (can apply to controversial research)
        see tobacco and sugar industry
        https://www.forbes.com/sites/stevensalzberg/2017/01/03/fake-medical-journals-are-spreading-and-they-are-filled-with-bad-science/#5cc8b57a30c9
