* boundary layer in fluid dynamics
http://www.mit.edu/course/1/1.061/www/dream/SEVEN/SEVENTHEORY.PDF
boundary layer: region of a (moving) fluid close to a stationary surface, where the velocity is lower
    fluid within the boundary layer moves more slowly
        no slip condition: velocity must be 0 on the surface
            because of viscosity, the fluid "sticks" to the surface
        velocity changes continuously from upstream velocity to 0
            height of boundary layer is when fluid velocity is 99% of free stream velocity
            spatial variation of velocity d\bar{u}/dz is called shear
                shear decreases with height above surface d(d\bar{u}/dz)/dz<0 (~logarithmic profile)
    friction with the surface generates turbulence according to the viscosity
    viscosity is irrelevant outside of the boundary layer
        aka prandtl’s hypothesis

in the boundary layer, turbulence is caused by shear (higher shear = higher turbulence)
    except close to the surface, where there is no turbulence
        viscosity prevents the formation of turbulence
            because of the no slip condition
        this region is called laminar sub-layer
    turbulence strength measured by u_rms = sqrt(\bar{u'^2}) \propto d\bar{u}/dz
        0 on the surface
        increases in the laminar sub-layer
        decreases to 0 at the end of the boundary layer
    shear velocity / friction velocity
        expresses the shear strength as a velocity
        determines the height of the laminar sub-layer
            higher friction velocity => thinner laminar sub-layer, more turbulence
    velocity as a function of distance to the surface
        increases linearly in the laminar sub-layer
        then increases logarithmically until the end of the boundary layer
            this area is called logarithmic sub-layer
            affected by the characteristic roughness of the surface
                depends on the relationship between the real roughness and the height of the laminar sub-layer
                    characteristic roughness does not depend on real roughness if real roughness is smaller than laminar sub-layer
                        smooth turbulent flow vs rough turbulent flow
            von Karman's constant

** laminar/turbulent flow
laminar flow: neat and tidy, all particles move in the same direction
turbulent flow: movement of particles is highly chaotic
    best studied through averages

high viscosity tends to give laminar flow, low viscosity turbolent flow
    viscosity: how much the molecules of the fluid "stick" together

Reynolds number can differentiate between the two flows
    Re = inertia forces / viscosity forces

* boundary layer meteorology
https://atmos.washington.edu/~breth/classes/AS547/
https://www.youtube.com/watch?v=EMhGTDVuE-4

studies conditions close to the surface => how the surface affects the atmosphere
    based on boundary layer in fluid dynamics, plus some additional complications such as
        - surface temperature, causing air to heat (unstable, more turbulence, daytime) or cool (stable, less turbulence, nighttime)
        - rotation of the earth, roughness of the surface, etc.
    height varies between ~100m to ~1km, highly depending on time of day
        surface layer: first ~50m, coriolis force is irrelevant
        air density can be assumed constant (varies in ~10km length scale)
    the atmospheric boundary layer is always turbulent
        because of instabilities, laminar flow would turn into turbulent flow
            shear instability: between surface and fluid
            kelvin-helmholtz instability: between fluid layers of different density
            convective (rayleigh-bernard) instability: when potential density decreases with height
                basically when a warmer fluid is below a colder one
        the ABL is not homogeneous, and a critical role of turbulence is to transport and mix stuff
    cannot be simulated in large scale models because turbulent motion happens at smaller scales
        so the effect is specified as a function of some "large scale" parameters
            aka parametrization
        e.g. in global circulation models
    study is conducted with respect to statistical properties of physical quantities
        because fluctuations are assumed to be random
        reynolds averaging: decompose quantity a into sum of ensemble mean plus variation due to turbulence: $a=\bar{a}+a'$
            e.g. \bar{a'a'} = variance of a, \bar{a'b'} = covariance between a and b, sqrt(\bar{a'^2}) = turbulence strength
            quantities depend on position and time, but indices are dropped to confuse people
            averages are taken over periods of ~10 minutes/1 hour, to separate fluctuations due to turbulence and non turbulence
                see temporal spectrum of atmospheric kinetic energy
        coordinate system is x = parallel to (average) horizontal wind, y = orthogonal to (avg.) horizontal wind, z = altitude
        u/w/v denote the wind velocity along the axes x/y/z
 
** surface fluxes
https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=2407&context=usdaarsfacpub
https://scienceofdoom.com/2010/04/09/sensible-heat-latent-heat-and-radiation/
http://twister.caps.ou.edu/MM2015/docs/chapter3/chapter3_c.pdf

flux: quantity passing through a surface
surface flux: exchange of ... with the atmosphere through the surface
    mostly energy in different forms, then the flux is measured in watts per square meter

radiative fluxes R: due to longwave and shortwave radiation
    positive when surface receives more energy than it irradiates (e.g. during hot days)

turbulent fluxes: due to wind speed and difference between temperature/vapor pressure of air and surface
    sensible heat flux H
        sensible heat = heat exchanged when the temperature of the system changes
        caused by conduction and convection
        aka kinematic heat flux
    latent heat flux LE
        latent heat = heat exchanged when the temperature of the system stays constant
            for example, during phase transition (e.g. water boiling)
        in the context of surface fluxes, LE flux is caused by water movements (condensation, evaporation, melting, etc.)
        aka kinematic flux of water vapor/moisture

soil heat flux G
    heat that is absorbed by surface (i.e. "moves" downwards inside earth)
    apparently quite hard to measure, see document above

surface energy balance
    R = G + H + LE
    incoming energy = outgoing energy

other fluxes of interest:
    momentum flux
    CO2 flux
    surface evaporation flux (difference with latent heat flux???)

*** surface energy budged
G - R = H + LE
observations do not add up, so there is an imbalance (between 15%/100% at cabauw) 
    see this document, section 15.1
    http://projects.knmi.nl/cabauw/insitu/observations/documentation/Cabauw_TR/Cabauw_TR.pdf

** turbulence kinetic energy budget
http://mafija.fmf.uni-lj.si/seminar/files/2011_2012/MaticSavli_2.pdf
how kinetic energy moves around due to turbulence, forcing conservation of momentum
use reynolds averaging to decompose wind velocity into mean velocity plus variation
    then total kinetic energy = mean kinetic energy + turbulent kinetic energy
budget (=variation over time) composed of
    shear production: due to the mean flow
        drag between fast and slow layers of air (moving horizontally)
    buoyancy flux/production: due to gravitational potential energy
        related to sensible and latent heat fluxes
            they change the mass of a parcel of air, thus its potential energy
        production in unstable conditions, consumption in stable conditions
    transport due to pressure gradient
        air moves from high pressure regions to low pressure regions
    transport due to turbulence/eddies
    dissipation
        turbulence decreases and tends to disappear with time due to viscosity
spectral decomposition: allows to see the difference in terms of eddy size
    large eddies = low frequency, small eddies = high frequency
    large eddies produce energy, small eddies dissipate it
        shear from large eddies produce smaller eddies, transferring energy from the "parent" eddy

** Monin-Obukhov similarity theory
under homogeneous and stationary conditions, every dimensionless group is an universal function of z/L
    sentence from "Exploring Self-Correlation in Flux–Gradient Relationships for Stably Stratified Conditions", Baas et al 2005
    https://link.springer.com/article/10.1007/s10546-006-9048-6
L is a length scale that depends on the local conditions
    interpretations
        determines the relative roles of shear and buoyancy in the production/consumption of turbulence kinetic energy
            sentence from http://glossary.ametsoc.org/wiki/Obukhov_length
        z/L is the production of turbulent kinetic energy due to buoyancy (hogstrom 1996, sec. 5.1)
            only true in stable conditions?
        proportional to the characteristic scale for the thickness of the dynamical sub-layer
            layer where the influence of stratification is negligible
            see 50 years, foken 2006
    when z/L >> 1, shear dominates
        we have the traditional log profile of wind
        conditions are stable, L positive, approaches infinity in the limit of neutral stratification
    when z/L << -1, buoyancy dominates
        main source of energy is convection
        unstable conditions, L negative

** objectives of boundary layer meteorology
want to get wind/temperature/humidity profiles (profile=value as a function of altitude)
    e.g. in neutral (calm) conditions, wind profile is logarithmic
    either actual profile or change with respect to altitude
want to get turbulent fluxes of shear and temperature
    those that appear in the turbulent kinetic energy budget, and have the largest impact on it
    roughly constant with altitude in the surface layer
    flux depends on vertical wind (because wind moves air duh)
    flux of a = \bar{w'a'} = covariance between variation in vertical wind speed and variation of quantity a
    legit to assume a causal relationship (?)
        aka eddy covariance, eddy correlation and eddy flux
want to get relationship between profile (easy to measure) and flux (important for weather/climate)
    can be obtained via dimensional analysis (= combine things such that units of measurements match)
        then do experiments to find coefficients so that things match
            obviously, experimental results disagree (in some circumstances)...
                *hypothesis* variations depend on factors that were not considered
    see e.g. Businger et al 1971, "Flux-profile relationship in the atmospheric surface layer"
        https://journals.ametsoc.org/doi/abs/10.1175/1520-0469%281971%29028%3C0181%3AFPRITA%3E2.0.CO%3B2

* data collection
** cabauw
cabauw observatory
    http://www.cesar-database.nl

data documentation:
    http://projects.knmi.nlcabauw/insitu/index2.htm
        observations -> documentation -> technical description
    gapfilling method
        http://projects.knmi.nl/cabauw/insitu/observations/documentation/gapfilling/cabcon_gapfilling.pdf

** arm
sgp30qcecor // Quality Controlled Eddy Correlation Flux Measurement- 30 min avg
thwaps // Temperature, humidity, winds and pressure system (THWAPS): meterological data 

* what I have to do / research question
use data to improve current flux-profile relationships, by incorporating more predictors
    specifically, predict wind shear and temperature gradient (aka lapse rate)
    errors reported in hogstrom 1996 are of a few tens percent
    main hypothesis: discrepancies found in experiments are due to factors that were not considered

*research question:* +phi_m and phi_h can be computed more accurately by incorporating new predictors+
can phi_m and phi_h, computed on the data from cabauw, be predicted more accurately by incorporating new predictors?

i.e. monin-obukhov similarity theory is not powerful enough

hogstrom 1996 dismisses this option as unlikely, except in very stable conditions


** DONE apparently the eddy correlation method to get flux intensity is quite inaccurate, do we bother?
alternatively, the surface energy budget is imbalanced
    will this cause problems?
maybe that's what she was referring to, when she mentioned imprecise measurement of u*
apparently this is not a significant factor (foken 2006, 50 years)
anyways, we will be able to integrate better methods to measure fluxes into our work pretty easily
*answer* nope

** TODO investigate approaches not using similarity theory
obukhov himself derived the phi functions outside of the similarity theory
    structure of the temp and vel. fields under conditions of free convection, 1960

** TODO find additional predictors
*** humidity
most works focus on dry air, although influences due to moisture are likely very small (foken 2006, 50 years)

** prediction 
*** block cross validation
we have a data point every 10 minutes, which means that points close in time are very similar one another
therefore we cannot assume that data is iid and make random splits
for example, nearest neighbors works incredibly well with k=1 (mse < 1e-3)
    and I assume methods based on kernel similarity would fare quite similarly
actually, every sample in the test set is almost guaranteed to have an almost identical sample in the training set

we should split data by time, e.g. by year/month/day
    for example, alternate one period train and one period test
        so that there are similar conditions in the training set
    DO NOT use data every 3/6/9/12/... days to test
        remember the 6 days cycle in wind/temperature measurements 
    cross-validation by year/month?
    note: just as samples close to any given test sample should not be in the training set, they shouldn't be in the test set either
        because errors are correlated
    also see https://stats.stackexchange.com/questions/14099/using-k-fold-cross-validation-for-time-series-model-selection

possible approach: h-block cross-validation
    https://www.ssc.wisc.edu/~bhansen/718/BurmanChowNolan1994.pdf
    basically, remove the h observation preceding and following each observation in the test set
    problem: how to choose h?
        we could side-step this and select a time interval using domain knowledge
    possible complication: assumes data is stationary, ours might not be
        stationary: unconditional joint distribution does not change over time
        we can verify it with some statistical tests
            which are gonna fail, remember the weird 6 days seasonality in wind/temperature measurements
        but is it a reasonable assumption?
    works for short-range dependencies (good for us)
    NB: shown to be inconsistent/not asymptotically optimal
        =use hv-block cross-validation instead=

moar paperz
   https://projecteuclid.org/download/pdfview_1/euclid.ssu/1268143839
   https://www.jstor.org/stable/2241910?seq=1#page_scan_tab_contents
   https://www.sciencedirect.com/science/article/pii/S0304407600000300
   https://ideas.repec.org/p/msh/ebswps/2015-10.html

*** similarity theory baseline
fit the functions found in the literature, find best coefficient thru least squares
probably better done when the data follows those functions more closely

*** k-nearest neighbors
given set of features
    F1: H, LE
    F2: air_dens, surf_temp, spec_hum, rel_hum, press, rain

h-5-fold nested cv, h = 1 week worth of samples, sorted by time

predicting phi_m
    clearly not using wind/ustar to predict phi_m since it heavily depends on it

F1 are very good predictors, using F1+F2 decreases MSE by ~5%, using F2 only MSE decreases by 25/30 %
    MSE(F1+F2) = 0.55/0.60, R2 scores are very low (around 0),
    18 mean percent error on average
        =just as good as similarity theory= 

*** neural network

validation data affects performance:
    - random months (even with just one): cannot go below 0.4
    - hk-fold and random samples: can go below 0.01 (with roughly the same samples in one month)

not sure using data from one full month is fair, because test samples are not independent between each other
OTOH, if the model was actually good, it shouldn't have troubles, but instead it overfits (badly)

experiment: change validation data and see how performance is affected
    use a different number of months
    use a wider interval for hk-fold CV

* limitations and future work
measures on land, but oceanic BL is quite different

our fluxes are obtained using eddy correlation technique, which is known to be not so good
    if new measurement techniques are introduced, we can re-train this system

we used data collected with smooth surface, but flux-profile relationships are not valid above very rough surface
    see https://link.springer.com/article/10.1007/BF00118340

the model does not explain its predictions, so it cannot be used to understand the physical laws, unlike formulas
    but it can be used in large scale climate models

* meetings
** 16/2
*my issue:* tried to compute phi vs z/L with cabauw data, but failed

look at measurements, some values are unrealistic, bad data points
u* small = no turbulence = formulas shouldnt work

USE THRESHOLDS !!! small values are hard to measure (eg low u* = no turbulence, hard to measure)

derivative of wind is speed@10 / 10m (because speed at surface is 0)

research question is good

*** post meeting
not sure the problem is bad data: if it were, there should be some good points among all the bad ones
** questions for next one

does fitting our own most parameters make sense? is it easily justified in the thesis?
    there's a lot of disagreement, but the papers are from the 80's

according to formulas, phi is always > 0, how can you have decreasing profiles then??
    e.g. temperature in unstable stratification decreases with height
    is it a limitation of the theory?

in order to have phi_m close to 0 when z/L is negative, you would need no wind or large u*, none of which is true
    is it a problem?

when computing L, should I use temperature at 2m or soil temperature?
    actually, I am computing L for every z, is it correct?

wind speed at 2 m is not there, but I am interpolating it with values from 10m and 0m
    because of this, gradient at 0m is the same as gradient at 2m
    is it a problem?

for h-k-fold cross validation, which value of h?
    currently using one week

used fluxes from eddy correlation, but we also have the bowen ratio, which should be used
    https://link.springer.com/content/pdf/10.1007/BF00709218.pdf
    
